/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.privacy.deep;import cn.zhuatech.privacy.common.ApiResponse;import org.springframework.web.bind.annotation.*;import java.time.*;/**
                                                                                                                                                    * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                    */
@RestController @RequestMapping("/api/admin/privacy-ops") public class DeepAdminController{private final DeepDomainService s;/**
                                                                                                                                                                                                                                                                                 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                 */
public DeepAdminController(DeepDomainService s){this.s=s;}/**
                                                                                                                                                                                                                                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                           */
@PostMapping("/assessments/{id}/approve")ApiResponse<?> assessment(@PathVariable Long id){return ApiResponse.ok(s.approveAssessment(id));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     */
@PostMapping("/activities/{id}/approve")ApiResponse<?> activity(@PathVariable Long id){return ApiResponse.ok(s.approveActivity(id));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          */
@PostMapping("/retention/run")ApiResponse<?> retention(@RequestParam String organizationCode,@RequestParam LocalDate asOf){return ApiResponse.ok(s.runRetention(organizationCode,asOf));}}
