/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.privacy.deep;import jakarta.persistence.*;import java.time.*;
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@Entity @Table(name="priv_processing_activities",uniqueConstraints=@UniqueConstraint(columnNames={"organizationCode","activityNo"})) class ProcessingActivity{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;@Version long version;String organizationCode,activityNo,name,department,owner,lawfulBasis,dataCategories,purpose,status="DRAFT";boolean sensitiveData,crossBorder;int retentionDays;LocalDateTime createdAt=LocalDateTime.now(),approvedAt;/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        */
protected ProcessingActivity(){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        */
ProcessingActivity(String o,String no,String n,String d,String owner,String basis,String categories,String purpose,boolean sensitive,boolean cross,int retention){organizationCode=o;activityNo=no;name=n;department=d;this.owner=owner;lawfulBasis=basis;dataCategories=categories;this.purpose=purpose;sensitiveData=sensitive;crossBorder=cross;retentionDays=retention;}}
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@Entity @Table(name="priv_impact_assessments",uniqueConstraints=@UniqueConstraint(columnNames="activityId")) class ImpactAssessment{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;Long activityId;String riskDescription,mitigations,residualRisk,status="DRAFT",reviewer;LocalDateTime assessedAt=LocalDateTime.now(),approvedAt;/**
                                                                                                                                                                                                                                                                                                                                                  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                  */
protected ImpactAssessment(){}/**
                                                                                                                                                                                                                                                                                                                                                                                * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                */
ImpactAssessment(Long a,String risk,String mitigations,String residual,String reviewer){activityId=a;riskDescription=risk;this.mitigations=mitigations;residualRisk=residual;this.reviewer=reviewer;}}
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@Entity @Table(name="priv_consents",uniqueConstraints=@UniqueConstraint(columnNames={"organizationCode","subjectRef","purposeCode","noticeVersion"})) class ConsentRecord{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;String organizationCode,subjectRef,purposeCode,noticeVersion,source,status="GRANTED",proofReference;LocalDateTime grantedAt=LocalDateTime.now(),revokedAt;/**
                                                                                                                                                                                                                                                                                                                                                                                                  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                  */
protected ConsentRecord(){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                             * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                             */
ConsentRecord(String o,String s,String p,String v,String source,String proof){organizationCode=o;subjectRef=s;purposeCode=p;noticeVersion=v;this.source=source;proofReference=proof;}}
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@Entity @Table(name="priv_subject_requests",uniqueConstraints=@UniqueConstraint(columnNames={"organizationCode","requestNo"})) class SubjectRequest{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;@Version long version;String organizationCode,requestNo,subjectRef,requestType,channel,status="RECEIVED",assignee,responseEvidence,rejectReason;LocalDateTime receivedAt=LocalDateTime.now(),dueAt=receivedAt.plusDays(30),verifiedAt,completedAt;/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    */
protected SubjectRequest(){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                */
SubjectRequest(String o,String no,String subject,String type,String channel){organizationCode=o;requestNo=no;subjectRef=subject;requestType=type;this.channel=channel;}}
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@Entity @Table(name="priv_deletion_tasks",uniqueConstraints=@UniqueConstraint(columnNames={"activityId","subjectRef","reason"})) class DeletionTask{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;Long activityId;String subjectRef,reason,status="QUEUED",evidenceReference;LocalDate scheduledDate;LocalDateTime completedAt;/**
                                                                                                                                                                                                                                                                                                                                               * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                               */
protected DeletionTask(){}/**
                                                                                                                                                                                                                                                                                                                                                                         * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                         */
DeletionTask(Long a,String subject,String reason,LocalDate date){activityId=a;subjectRef=subject;this.reason=reason;scheduledDate=date;}}
